### ISSUE TITLE
Ability to search for tags + tag fuzzy matching

### ISSUE THREAD

**Issue by mudkipdev** [mudkipdev/leaf#9]
This issue will introduce a new command named `/tags search <query: str>`. When used, it will fuzzy match tags that are similar to the query listed in the same format as the `/tags list` command.

This issue should also introduce a fuzzy matching feature to the `/tags view` command that will show a "did you mean..." message when a tag does not exist.

Part of #1.

**Comment by mudkipdev** [comment]
For the search, maybe we could just add it as an argument to `/tags list`, but it will get more confusing with too many arguments.

**Comment by bsrecker** [comment]
@mudkipdev /tags list probably does not need the fuzzy match since its just returning every tag anyways.
